### ISSUE TITLE
Device: 0 has completed its nonce range

### ISSUE THREAD

**Issue by tuxd3v** [CryptoGraphics/lyclMiner#18]
Hello, I am receiving at each new block this information:
[2019-02-18 06:36:03] Device: 0 max runs: 4096
[2019-02-18 06:36:03] Device: 0 has completed its nonce range

Rx580 4GB:
<Device0 DeviceIndex = "1" BinaryFormat = "amdcl2" AsmProgram = "gfx8" WorkSize = "1024">

Is this any problem?
thanks in Advance
regards

**Comment by CryptoGraphics** [comment]
Hello. Every device works within its own nonce range.
This is a debug information which shows that GPU is actually working and not stuck/frozen.
Once numRuns*workSize hashes is computed lyclMiner will report that device has completed its nonce range and then generate a new one. You can also see this during initialization/startup.
