### ISSUE TITLE
Failed to open file for reading: kernels/blake32/blake32.cl

### ISSUE THREAD

**Issue by shimmervoid** [CryptoGraphics/lyclMiner#5]
Thanks for providing this miner. I encounter the following error when executed:

Failed to open file for reading: kernels/blake32/blake32.cl
Failed to create CL program from source(blake32). Device(gfx900) Platform index(0)
[2018-06-22 04:18:27] Failed to initialize device(1)! Skipping...
Failed to open file for reading: kernels/blake32/blake32.cl
Failed to create CL program from source(blake32). Device(gfx900) Platform index(0)
[2018-06-22 04:18:27] Failed to initialize device(0)! Skipping...
Failed to open file for reading: kernels/blake32/blake32.cl
Failed to create CL program from source(blake32). Device(gfx900) Platform index(0)
[2018-06-22 04:18:27] Failed to initialize device(2)! Skipping...
Failed to open file for reading: kernels/blake32/blake32.cl
Failed to create CL program from source(blake32). Device(gfx900) Platform index(0)
[2018-06-22 04:18:27] Failed to initialize device(3)! Skipping...

Running on Ubuntu 18.04|4.13.0-0413|ROCm 1.8.1

Any help will be appreciated.

**Comment by CryptoGraphics** [comment]
Make sure that "kernels" folder is in the same directory as lyclMiner executable.

**Comment by shimmervoid** [comment]
Thanks, I'm not sure how i omitted that step
