### ISSUE TITLE
-g only generates one AMD output

### ISSUE THREAD

**Issue by BobbyGR** [CryptoGraphics/lyclMiner#6]
1. Device: Ellesmere
    Board name: Radeon RX 580 Series
  PCIe bus ID: 0
   Available platforms indices: 1, 1, 1, 1, 1, 1
Device0 PCIeBusId = "0" PlatformIndex = "1" BinaryFormat = "amdcl2" AsmProgram = "gfx8" WorkSize = "1048576">

**Comment by BobbyGR** [comment]
5 cards it generates fine, but 6 I can't get it to generate correctly

**Comment by CryptoGraphics** [comment]
What platform are you using? Linux or Windows?

Do you have an error during the config file generation?
Error CL_DEVICE_TOPOLOGY_AMD!

**Comment by BobbyGR** [comment]
Windows, no error that I can see.  I was able to duplicate on two rigs both with 6 GPU's in the them

**Comment by BobbyGR** [comment]
![image](https://user-images.githubusercontent.com/16457262/41819253-3881f9d2-778b-11e8-8dd6-e8df78659508.png)

**Comment by BobbyGR** [comment]
![image](https://user-images.githubusercontent.com/16457262/41819263-65ce7302-778b-11e8-8e5d-4345a9ad0438.png)

**Comment by CryptoGraphics** [comment]
Can you try the latest version?

**Comment by BobbyGR** [comment]
Looks good to me, tested it multiple times.  thanks for the quick turnaround
