### ISSUE TITLE
Build Errors on Ubuntu 14.04

### ISSUE THREAD

**Issue by ultraboby** [CryptoGraphics/lyclMiner#8]
==== Building lyclMiner (release) ====
AppLyra2REv2.cpp
In file included from ../../src/lyclApplets/AppLyra2REv2.cpp:10:0:
../../src/lyclApplets/AppLyra2REv2.hpp: In member function ‘bool lycl::AppLyra2REv2::onInit(const lycl::device&)’:
../../src/lyclApplets/AppLyra2REv2.hpp:145:111: error: ‘clCreateCommandQueueWithProperties’ was not declared in this scope
         m_clCommandQueue = clCreateCommandQueueWithProperties(m_clContext, in_device.clId, nullptr, &errorCode);
                                                                                                               ^
make[1]: *** [obj/Release/AppLyra2REv2.o] Error 1
make: *** [lyclMiner] Error 2

**Comment by CryptoGraphics** [comment]
It seems that your OpenCL headers are too old.

It is recommended to install Ubuntu 16.04 or higher.
For the best performance you need AMDGPU-Pro 18.20(or higher) or ROCm 1.8.

**Comment by CryptoGraphics** [comment]
You need OpenCL headers with 2.0+ support.

Ubuntu 14.04 provides only 1.2
https://packages.ubuntu.com/trusty/opencl-headers

Alternatively you can open file **src/lyclApplets/AppLyra2REv2.hpp**
find this line:
`m_clCommandQueue = clCreateCommandQueueWithProperties(m_clContext, in_device.clId, nullptr, &errorCode);`
 and change it to:
`m_clCommandQueue = clCreateCommandQueue(m_clContext, in_device.clId, 0, &errorCode);`

**Comment by ultraboby** [comment]
../../src/lyclCore/OtherThreads.hpp:146:102: error: cannot pass objects of non-trivially-copyable type ‘std::string {aka class std::basic_string<char>}’ through ‘...’
                 Log::print(Log::LT_Blue, "Connection changed to %s", global::connectionInfo.short_url);

**Comment by CryptoGraphics** [comment]
Fixed in 0.2.0.
