### ISSUE TITLE
MSVCR120.dll not found (alternative names)

### ISSUE THREAD

**Issue by HyperGamers** [CryptoGraphics/lyclMiner#9]
I started on a fresh install of Windows and had also installed latest AMD 18.6.1 Radeon Software Adrenalin drivers which comes with Visual C++ 2015 Redistributable x86 package.

On running the miner it said, "MSVCR120.dll not found"

Then manually installing 2017 redistributable packages gets stuck after showing developer info.
I searched for the MSVCR120.dll file and it didn't exist.

However, I did find a msvcr120_clr0400.dll which I copied and pasted into the lyclminer folder and renamed to MSVCR120.dll and it worked.

I'm not entirely sure on how the whole thing works but is there a way to check for both uppercase and lowercase:
"msvcr120*.dll"

where * can be other strings also?

**Comment by HyperGamers** [comment]
@tpruvot ahh, that's why the 2017 didn't work properly. But I didn't install the 2013 version and the AMD installer came with 2015, and I think one of them worked after renaming

**Comment by CryptoGraphics** [comment]
Hello.

Check out the latest build.

**Comment by HyperGamers** [comment]
@CryptoGraphics

I'm not really that used to GitHub or how it works though I have used it now and then. It says last commit 20 days ago, I'm guessing it's still getting pushed? Anyways can't wait for the next version.

Thanks very much for your hard work

**Comment by CryptoGraphics** [comment]
It is already updated. Link and date were left unchanged.

This issue has nothing to do with the miner itself.
libcurl was compiled with OpenSSL(which miner no longer uses), which in turn used MSVCR120.

**Comment by HyperGamers** [comment]
Awesome thanks :)
